### ISSUE TITLE
💅🏻 CSS specificity is a #$@&%*!

### ISSUE THREAD

**Issue by astroash** [fac-13/CourtWatch#58]
If you're writing your own CSS always use classnames, and don't style on elements or ids. This is because CSS specificity kicks in, which is a hierarchy of which css definitions are more important, meaning that your CSS will not always be overwritten from top to bottom. 

You can read about it here:
https://medium.com/@dte/understanding-css-selector-specificity-a02238a02a59

**Comment by GiuliaTeggi** [comment]
Thank you! I'll add classnames to all the elements in the SCSS. :wink:
